### ISSUE TITLE
Update setup-glassfish.py as RC4 Ciphers are deprecated

### ISSUE THREAD

**Issue by wayne-chung** [icatproject/installer#3]
The setup-glassfish.py script found at http://icatproject.org/misc/scripts/setup-glassfish.py needs to be updated to use the newer ciphers.

**Comment by tomgriffinstfc** [comment]
The instructions on http://icatproject.org/installation/glassfish/ also need updating

**Comment by fisherab** [comment]
The script and the instructions are now up to date but not the installer itself
